sravan_c_dbt:
  outputs:
    dev:
      catalog: dbt_c_dev
      host: xxxxxxxxxxxxxxxxxxxxxxx.cloud.databricks.com
      http_path: /sql/1.0/warehouses/1271f87819e069ba
      schema: default
      threads: 1
      token: xxxxxxxxxxxxxxxxxxxxxxxxx
      type: databricks
    prod:
      catalog: dbt_c_prod
      host: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.cloud.databricks.com
      http_path: /sql/1.0/warehouses/1271f87819e069ba
      schema: default
      threads: 1
      token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      type: databricks
  target: dev
